### ISSUE TITLE
unable to install 

### ISSUE THREAD

**Issue by waqarr** [DRM-Scripts/Universal-DRM#1]
here is error detail 

`
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: request-promise-retry@1.0.0
npm WARN Found: request-promise@4.2.4
npm WARN node_modules/request-promise
npm WARN   request-promise@"^4.2.2" from the root project
npm WARN   1 more (promise-request-retry)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer request-promise@"^2.0.1" from request-promise-retry@1.0.0
npm WARN node_modules/request-promise-retry
npm WARN   request-promise-retry@"^1.0.0" from the root project
npm WARN
npm WARN Conflicting peer dependency: request-promise@2.0.1
npm WARN node_modules/request-promise
npm WARN   peer request-promise@"^2.0.1" from request-promise-retry@1.0.0
npm WARN   node_modules/request-promise-retry
npm WARN     request-promise-retry@"^1.0.0" from the root project
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/BrandonOCasey/jsdoc.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-17T12_38_56_159Z-debug-0.log
`

**Comment by DRM-Scripts** [comment]
What OS are you installing on? It's been teste don U20.04/22.04

**Comment by waqarr** [comment]
i tried on 22.04

**Comment by DRM-Scripts** [comment]
Try on 18.04 or 20.04 and you shouldn't have any issues, seems a repo is tempremental and keeps removing its u22.04 package.
