### ISSUE TITLE
Error getting stream :(

### ISSUE THREAD

**Issue by torephp** [DRM-Scripts/Universal-DRM#2]
I have a problem, when I press start I get a message: error getting stream , if I copy the url of the stream this appears to me: Cannot GET /static/sling-1f7b8a15201545c6a10d5b50db859e8b/playlist.m3u8

**Comment by torephp** [comment]
> I have a problem, when I press start I get a message: error getting stream, se copia url dello stream e provo ad aprilo mi appare questo messaggio: Cannot GET /static/sling-1f7b8a15201545c6a10d5b50db859e8b/playlist.m3u8

**Comment by thejackal2017** [comment]
Sorry ,but may i ask what is the version of npm,node js and pm2 installed on your System ? 
you can get the info by typing the following commands in the terminal: 

```
npm -v
node -v
pm2 -v 

```
Regards

**Comment by thejackal2017** [comment]
Sorry ,but may i ask what is the version of npm,node js and pm2 installed on your System ? 
you can git the info by typing the following commands in the terminal: 

```
npm -v
node -v
pm2 -v 

```
Regards

**Comment by DRM-Scripts** [comment]
> I have a problem, when I press start I get a message: error getting stream , if I copy the url of the stream this appears to me: Cannot GET /static/sling-1f7b8a15201545c6a10d5b50db859e8b/playlist.m3u8

This means the stream hasn’t generated or been blocked when it’s tried to create. If you start the script by running node src/server.js and not via pm2 command then you will see a running log and have an understanding what’s causing the issues (likely sling has blocked the server ip range already from the host).
