### ISSUE TITLE
Hello, I know you don't provide technical support, but I want to ask a question, thank you

### ISSUE THREAD

**Issue by iptvtest123** [DRM-Scripts/Universal-DRM#3]
**0|Universal-DRM  | [78699] Failed to execute script sports
0|Universal-DRM  | Traceback (most recent call last):
0|Universal-DRM  |   File "sports.py", line 40, in <module>
0|Universal-DRM  |   File "pywidevine/decrypt/wvdecrypt.py", line 39, in sports_decrypt
0|Universal-DRM  |   File "pywidevine/decrypt/wvdecrypt.py", line 12, in check_pssh
0|Universal-DRM  | ValueError: byte must be in range(0, 256)
0|Universal-DRM  |  `binaries/linux/foobar -p AAADMnBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAxISAwAAAQABAAgDPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwATABBAF8AVQBSAEwAPgBoAHQAdABwADoALwAvAHAALQBwAGwAYQB5AHIAZQBhAGQAeQAuAG0AbwB2AGUAdAB2AC4AYwBvAG0ALwBwAGwAYQB5AHIAZQBhAGQAeQAvAHIAaQBnAGgAdABzAG0AYQBuAGEAZwBlAHIALgBhAHMAbQB4ADwALwBMAEEAXwBVAFIATAA+ADwATABVAEkAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AcAAtAHAAbABhAHkAcgBlAGEAZAB5AC4AbQBvAHYAZQB0AHYALgBjAG8AbQAvAGwAbwBnAGkAbgAuAGEAcwBwAHgAPAAvAEwAVQBJAF8AVQBSAEwAPgA8AEsASQBEAD4AZABLADgATgBiAHoAUgBqAGgAVQBTAHkAMQB0ADIAWgByAFoAZgBUADYAQQA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgBPAGQAZQA1AGoAUwBtAHEANABrAEEAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA= -l http://localhost:3001/sling/yGsZQrFlUn` (exited with error code 255)
0|Universal-DRM  |     at callback (/home/Universal-DRM/node_modules/child-process-promise/lib/index.js:33:27)
0|Universal-DRM  |     at ChildProcess.exithandler (child_process.js:301:5)
0|Universal-DRM  |     at ChildProcess.emit (events.js:198:13)
0|Universal-DRM  |     at maybeClose (internal/child_process.js:982:16)
0|Universal-DRM  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
0|Universal-DRM  |   name: 'ChildProcessError',
0|Universal-DRM  |   code: 255,
0|Universal-DRM  |   childProcess:
0|Universal-DRM  |    { ChildProcess: { [Function: ChildProcess] super_: [Function] },
0|Universal-DRM  |      fork: [Function: fork],
0|Universal-DRM  |      _forkChild: [Function: _forkChild],
0|Universal-DRM  |      exec: [Function: exec],
0|Universal-DRM  |      execFile: [Function: execFile],
0|Universal-DRM  |      spawn: [Function: spawn],
0|Universal-DRM  |      spawnSync: [Function: spawnSync],
0|Universal-DRM  |      execFileSync: [Function: execFileSync],
0|Universal-DRM  |      execSync: [Function: execSync] },
0|Universal-DRM  |   stdout: '',
0|Universal-DRM  |   stderr:
0|Universal-DRM  |    '[78699] Failed to execute script sports\nTraceback (most recent call last):\n  File "sports.py", line 40, in <module>\n  File "pywidevine/decrypt/wvdecrypt.py", line 39, in sports_decrypt\n  File "pywidevine/decrypt/wvdecrypt.py", line 12, in check_pssh\nValueError: byte must be in range(0, 256)\n' }
**

**Comment by DRM-Scripts** [comment]
Whats the question, as youv'e posted an error but asked no question...
