### ISSUE TITLE
Hilarious

### ISSUE THREAD

**Issue by Neo-1977** [DRM-Scripts/Universal-DRM#4]
Nice of you to reupload the same Code from my page.. 

Why dont you actually try developing something off your own back.

**Comment by DRM-Scripts** [comment]
Apologies, I don’t claim to have created this, it was sent to me to upload with no binaries and that’s all I’ve included. Happy to credit yourself as I had no idea who the original creator was/is.

Edit: actually I did know this was you if I was being a rtard as I’ve seen a earlier version of it from yourself. I’ll credit and link to you page again apologies.
